# Generated by Django 4.2.6 on 2024-02-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clg_name', models.CharField(max_length=100)),
                ('clg_location', models.CharField(max_length=100)),
                ('clg_principal', models.CharField(max_length=100)),
                ('clg_code', models.IntegerField()),
            ],
        ),
    ]
